trigger: none

pool: 
  name: Default
  demands:
    - agent.name -equals TestBuildArt

#pool: 
#    vmImage: 'macos-latest'

#variables:
#    DownloadBuildArtifacts.ForceEnableDownloadZipForCanary : 'true'

strategy:
  matrix:
    'Artifact with +':
      artifactName: 'drop + 9234857'
    #'Artifact with !':
    #  artifactName: 'drop ! 9234857'
    #'Artifact with @':
    #  artifactName: 'drop @ 9234857'
    #'Artifact with #':
    #  artifactName: 'drop # 9234857'
    #'Artifact with %':
    #  artifactName: 'drop % 9234857'
    #'Artifact with ^':
    #  artifactName: 'drop ^ 9234857'
    #'Artifact with :':
    #  artifactName: 'drop : 9234857'
    #'Artifact with ?':
    #  artifactName: 'drop ? 9234857'
    #'Artifact with ()':
    #  artifactName: 'drop () 9234857'
    #'Artifact with *':
    #  artifactName: 'drop * 9234857'
    #'Artifact with $':
    #  artifactName: 'drop $ 9234857'
    #'Artifact with -+=':
    #  artifactName: 'drop -+= 9234857'
    #'Artifact with /':
    #  artifactName: 'drop / 9234857'
    #'Artifact with \':
    #  artifactName: 'drop \ 9234857'
    #'Artifact with |':
    #  artifactName: 'drop | 9234857'
    #'Artifact with ,':
    #  artifactName: 'drop , 9234857'
    #'Artifact with .':
    #  artifactName: 'drop . 9234857'
    #'Artifact with `':
    #  artifactName: 'drop ` 9234857'
    #'Artifact with ~':
    #  artifactName: 'drop ~ 9234857'

steps:

# publish artifact to container
- task: PublishBuildArtifacts@1
  name: 'Pipeline_PublishBuildArtifacts'
  condition: always()
  timeoutInMinutes: 1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: $(artifactName)
    publishLocation: 'Container'

# download artifact from container
- task: DownloadBuildArtifacts@0 #.206.0
  name: 'Pipeline_DownloadBuildArtifacts'
  condition: always()
  timeoutInMinutes: 1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: $(artifactName)
    downloadPath: '$(System.ArtifactsDirectory)'

#- task: DownloadBuildArtifacts@0 #.206.0
#  condition: always()
#  timeoutInMinutes: 1
#  inputs:
#    buildType: 'specific'
#    project: '3e0295ab-3dd6-43ce-86af-16273f5f1b23'
#    pipeline: '33'
#    buildVersionToDownload: 'latest'
#    allowPartiallySucceededBuilds: true
#    downloadType: 'single'
#    artifactName: 'drop & 9234857'
#    downloadPath: '$(System.ArtifactsDirectory)'


# publish artifact to file path
- task: PublishBuildArtifacts@1
  name: 'FileShare_PublishBuildArtifacts'
  condition: always()
  timeoutInMinutes: 1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: '$(artifactName)2'
    publishLocation: 'FilePath'
    TargetPath: '$(Pipeline.Workspace)'

# download artifact from file path
- task: DownloadBuildArtifacts@0 #.206.0
  name: 'FileShare_DownloadBuildArtifacts'
  condition: always()
  timeoutInMinutes: 1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: '$(artifactName)2'
    downloadPath: '$(System.ArtifactsDirectory)'

# download multiple artifacts from this build
- task: DownloadBuildArtifacts@0
  name: 'All_DownloadBuildArtifacts'
  condition: always()
  timeoutInMinutes: 1
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'

# download multiple artifacts from previous run of this build
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '3e0295ab-3dd6-43ce-86af-16273f5f1b23'
    pipeline: '35'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'

# download single artifact from previous run of this build
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '3e0295ab-3dd6-43ce-86af-16273f5f1b23'
    pipeline: '35'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    downloadType: 'single'
    artifactName: '$(artifactName)'
    downloadPath: '$(System.ArtifactsDirectory)'
